version: '3.8'

services:
  webreconlite:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webreconlite
    ports:
      - "8001:8001"
    volumes:
      - ./app/results:/app/app/results
    environment:
      - SECRET_KEY=webreconlite-production-key
      - DEBUG=False
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - webreconlite-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/tools" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  webreconlite-network:
    driver: bridge

volumes:
  results-data:
